name: check-build
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++-10 --version
      - run: pwd
      - run: make clean all
      - name: run-tests
        run: ./solve_test
        shell: bash
